DOMAIN_DISCRETIZATION: elevation
DOMAIN_NAME: Bow_at_Banff
ELEVATION_BAND_SIZE: 300
EXPERIMENT_ID: initial_run
FORCING_DATASET: RDRS
FORCING_END_YEAR: '2020'
FORCING_START_YEAR: '2010'
HYDROLOGICAL_MODEL: SUMMA
MIN_HRU_SIZE: 2
ROUTING_MODEL: mizuroute
