BOUNDING_BOX_COORDS: 9.83/-13.46/34.83/-2.27
CATCHMENT_PLOT_DIR: default
CLEANUP_INTERMEDIATE_FILES: true
CONFLUENCE_CODE_DIR: /Users/darrieythorsson/compHydro/code/CONFLUENCE
CONFLUENCE_DATA_DIR: /Users/darrieythorsson/compHydro/data/CONFLUENCE_data
DELINEATE_BY_POURPOINT: true
DEM_NAME: elevation.tif
DEM_PATH: default
DOMAIN_DEFINITION_METHOD: delineate
DOMAIN_DISCRETIZATION: landclass
DOMAIN_NAME: Congo
FORCING_DATASET: ERA5
FORCING_END_YEAR: 2022
FORCING_START_YEAR: 1979
GEOFABRIC_TYPE: TDX
HYDROLOGICAL_MODEL: SUMMA
LUMPED_WATERSHED_METHOD: pysheds
MIN_HRU_SIZE: '10'
OUTPUT_BASINS_PATH: default
OUTPUT_DIR: default
OUTPUT_RIVERS_PATH: default
POUR_POINT_COORDS: -5.795556/12.204722
POUR_POINT_SHP_NAME: default
POUR_POINT_SHP_PATH: default
ROUTING_MODEL: mizuroute
SOURCE_GEOFABRIC_BASINS_PATH: /Users/darrieythorsson/compHydro/data/CWARHM_data/domain_NorthAmerica/shapefiles/catchment/7020021430-basins.gpkg
SOURCE_GEOFABRIC_RIVERS_PATH: /Users/darrieythorsson/compHydro/data/CWARHM_data/domain_NorthAmerica/shapefiles/river_network/7020021430-streamnet.gpkg
STREAM_THRESHOLD: 5000
TAUDEM_DIR: default
