APPLY_LAPSE_RATE: true
BASIN_PARAMS_TO_CALIBRATE: basin__aquiferHydCond,basin__aquiferBaseflowExp,basin__aquiferScaleFactor
BOUNDING_BOX_COORDS: 52.50/51.20/-0.50/-1.80
CALIBRATION_PERIOD: 2018-01-01, 2018-06-30
CATCHMENT_PATH: default
CATCHMENT_PLOT_DIR: default
CATCHMENT_SHP_AREA: HRU_area
CATCHMENT_SHP_GRUID: GRU_ID
CATCHMENT_SHP_HRUID: HRU_ID
CATCHMENT_SHP_LAT: center_lat
CATCHMENT_SHP_LON: center_lon
CATCHMENT_SHP_NAME: Chena_HRUs_elevation.shp
CLEANUP_INTERMEDIATE_FILES: true
COMBINED_DISCRETIZATION_METHODS: elevation, radiation
CONFLUENCE_CODE_DIR: /home/darri/code/CONFLUENCE
CONFLUENCE_DATA_DIR: /home/darri/data/CONFLUENCE_data
DATATOOL_CACHE: /home/darri/cache/
DATATOOL_DATASET_ROOT: /project/rrg-mclark/data/meteorological-data/
DATATOOL_PATH: default
DATA_ACQUIRE: HPC
DDS_R: 0.2
DECISION_OPTIONS:
  compaction:
  - consettl
  - anderson
  snowIncept:
  - lightSnow
  - stickySnow
  windPrfile:
  - logBelowCanopy
  - exponential
DELINEATE_BY_POURPOINT: true
DEM_NAME: domain_Chena_elv.tif
DEM_PATH: default
DIAGNOSTIC_FREQUENCY: 10
DOMAIN_DEFINITION_METHOD: delineate
DOMAIN_DISCRETIZATION: elevation
DOMAIN_NAME: Thames
EASYMORE_CACHE: /home/darri/easymore/
EASYMORE_CLIENT: easymore cli
EASYMORE_JOB_CONF: installs/MAF/02_model_agnostic_component/easymore-job.slurm
ELEVATION_BAND_SIZE: 100
EVALUATION_PERIOD: 2018-07-01, 2018-12-31
EXE_NAME_MIZUROUTE: mizuroute.exe
EXPERIMENT_BACKUP_SETTINGS: true
EXPERIMENT_ID: run_1
EXPERIMENT_LOG_MIZUROUTE: default
EXPERIMENT_LOG_SUMMA: default
EXPERIMENT_OUTPUT_MIZUROUTE: default
EXPERIMENT_OUTPUT_SUMMA: default
EXPERIMENT_TIME_END: 2018-12-31 23:00
EXPERIMENT_TIME_START: 2018-01-01 01:00
FLASH_BATCH_SIZE: 64
FLASH_DROPOUT: 0.2
FLASH_EPOCHS: 300
FLASH_HIDDEN_SIZE: 128
FLASH_L2_REGULARIZATION: 1e-6
FLASH_LEARNING_PATIENCE: 30
FLASH_LEARNING_RATE: 0.001
FLASH_LOAD: true
FLASH_LOOKBACK: 700
FLASH_NUM_LAYERS: 3
FLASH_USE_ATTENTION: true
FORCE_RUN_ALL_STEPS: false
FORCING_DATASET: ERA5
FORCING_END_YEAR: '2018'
FORCING_MEASUREMENT_HEIGHT: 1.5
FORCING_PATH: default
FORCING_SHAPE_LAT_NAME: lat
FORCING_SHAPE_LON_NAME: lon
FORCING_START_YEAR: '2018'
FORCING_TIME_STEP_SIZE: 3600
FORCING_VARIABLES: longitude,latitude,time,LWRadAtm,SWRadAtm,pptrate,airpres,airtemp,spechum,windspd
GEOFABRIC_MAPPING:
  area:
    in_units: m^2
    in_varname: HRU_area
    out_units: m^2
  basinID:
    in_varname: GRU_ID
  nextDownID:
    in_varname: DSLINKO
  rivlen:
    in_units: m
    in_varname: Length
    out_units: m
GEOFABRIC_TYPE: TDX
GISTOOL_DATASET_ROOT: /project/rrg-mclark/data/geospatial-data/
GISTOOL_LIB_PATH: /project/rrg-mclark/lib/
GISTOOL_PATH: default
HYDROLOGICAL_MODEL: SUMMA
INSTALL_PATH_MIZUROUTE: default
INTERSECT_DEM_NAME: catchment_with_dem.shp
INTERSECT_DEM_PATH: default
INTERSECT_LAND_NAME: catchment_with_landclass.shp
INTERSECT_LAND_PATH: default
INTERSECT_ROUTING_NAME: catchment_with_routing_basins.shp
INTERSECT_ROUTING_PATH: default
INTERSECT_SOIL_NAME: catchment_with_soilclass.shp
INTERSECT_SOIL_PATH: default
ITERATION_RESULTS_FILE: default
LANDCOVER_YEAR: '2020'
LAND_CLASS_NAME: domain_Chena_land_classes.tif
LAND_CLASS_PATH: default
LAPSE_RATE: 0.0065
LUMPED_WATERSHED_METHOD: pysheds
MINIMUM_LAND_FRACTION: 0.01
MIN_HRU_SIZE: '2'
MOO_OPTIMIZATION_METRICS: KGE,NSE
MPI_PROCESSES: 8
NGSIZE: 10
NUMBER_OF_GENERATIONS: 10
NUMBER_OF_ITERATIONS: 100
NUMBER_OF_OBJECTIVES: 2
NUM_LAND_COVER: 20
OBSERVATIONS_PATH: default
OPTIMIZATION_METRIC: KGE
OPTIMIZATION_RESULTS_FILE: default
OPTMIZATION_ALOGORITHM: NSGA-II
OSTRICH_ALGORITHM: ParallelDDS
OSTRICH_EXE: OstrichMPI
OSTRICH_METRICS: GCOP
OSTRICH_OUTPUT_FILE: ostrich_output.txt
OSTRICH_PATH: default
OUTPUT_BASINS_PATH: default
OUTPUT_DIR: default
OUTPUT_RIVERS_PATH: default
PARAMS_TO_CALIBRATE: newSnowDenMin,newSnowDenMultTemp,Fcapil,k_snow,soil_dens_intr,albedoDecayRate,tempCritRain,k_soil,vGn_n,theta_sat,theta_res,zScale_TOPMODEL,k_macropore
POPULATION_SIZE: 100
POUR_POINT_COORDS: 51.486667/-0.310000
POUR_POINT_SHP_NAME: default
POUR_POINT_SHP_PATH: default
PSO_COGNITIVE_PARAM: 2.0
PSO_CONSTRICTION_FACTOR: 1.0
PSO_CONVERGENCE_VAL: 0.0001
PSO_INERTIA_REDUCTION_RATE: 0.1
PSO_INERTIA_WEIGHT: 1.2
PSO_INIT_POPULATION_METHOD: Random
PSO_NUM_GENERATIONS: 50
PSO_SOCIAL_PARAM: 2.0
PSO_SWARM_SIZE: 20
RADIATION_CLASS_NUMBER: 5
RADIATION_PATH: default
RIVER_BASINS_NAME: Chena_riverBasins_delineate.shp
RIVER_BASINS_PATH: default
RIVER_BASIN_SHP_AREA: GRU_area
RIVER_BASIN_SHP_HRU_TO_SEG: gru_to_seg
RIVER_BASIN_SHP_RM_GRUID: GRU_ID
RIVER_NETWORK_SHP_DOWNSEGID: DSLINKNO
RIVER_NETWORK_SHP_LENGTH: Length
RIVER_NETWORK_SHP_NAME: Chena_riverNetwork_delineate.shp
RIVER_NETWORK_SHP_PATH: default
RIVER_NETWORK_SHP_SEGID: LINKNO
RIVER_NETWORK_SHP_SLOPE: Slope
ROUTING_MODEL: mizuroute
RUN_DECISION_ANALYSIS: true
RUN_SENSITIVITY_ANALYSIS: true
SCE_BUDGET: 10000
SCE_LOOP_STAGNATION: 5
SCE_MIN_COMPLEXES: 3
SCE_NUM_COMPLEXES: 3
SCE_NUM_EVOLUTION_STEPS: 19
SCE_PCT_CHANGE: 0.01
SCE_POINTS_PER_COMPLEX: 19
SCE_POINTS_PER_SUBCOMPLEX: 10
SCE_POP_CONV: 0.001
SCE_USE_INITIAL_POINT: false
SETTINGS_MIZU_CONTROL_FILE: mizuroute.control
SETTINGS_MIZU_MAKE_OUTLET: n/a
SETTINGS_MIZU_NEEDS_REMAP: false
SETTINGS_MIZU_OUTPUT_FREQ: single
SETTINGS_MIZU_OUTPUT_VARS: 1
SETTINGS_MIZU_PARAMETERS: param.nml.default
SETTINGS_MIZU_PATH: default
SETTINGS_MIZU_REMAP: routing_remap.nc
SETTINGS_MIZU_ROUTING_DT: 3600
SETTINGS_MIZU_ROUTING_UNITS: m/s
SETTINGS_MIZU_ROUTING_VAR: averageRoutedRunoff
SETTINGS_MIZU_TOPOLOGY: topology.nc
SETTINGS_MIZU_WITHIN_BASIN: 0
SETTINGS_SUMMA_ATTRIBUTES: attributes.nc
SETTINGS_SUMMA_BASIN_PARAMS_FILE: basinParamInfo.txt
SETTINGS_SUMMA_COLDSTATE: coldState.nc
SETTINGS_SUMMA_CONNECT_HRUS: true
SETTINGS_SUMMA_CPUS_PER_TASK: 32
SETTINGS_SUMMA_FILEMANAGER: fileManager.txt
SETTINGS_SUMMA_FORCING_LIST: forcingFileList.txt
SETTINGS_SUMMA_GRU_COUNT: 118
SETTINGS_SUMMA_GRU_PER_JOB: 10
SETTINGS_SUMMA_LOCAL_PARAMS_FILE: localParamInfo.txt
SETTINGS_SUMMA_MEM: 0
SETTINGS_SUMMA_OUTPUT: outputControl.txt
SETTINGS_SUMMA_PARALLEL_EXE: summa_actors.exe
SETTINGS_SUMMA_PARALLEL_PATH: default
SETTINGS_SUMMA_PATH: default
SETTINGS_SUMMA_TIME_LIMIT: 01:00:00
SETTINGS_SUMMA_TRIALPARAMS: trialParams.nc
SETTINGS_SUMMA_TRIALPARAM_1: maxstep,900
SETTINGS_SUMMA_TRIALPARAM_N: 1
SETTINGS_SUMMA_USE_PARALLEL_SUMMA: false
SIMULATIONS_PATH: default
SIM_REACH_ID: 229
SOIL_CLASS_NAME: domain_Chena_soil_classes.tif
SOIL_CLASS_PATH: default
SOURCE_GEOFABRIC_BASINS_PATH: /project/6079554/data/geospatial-data/MERIT-Basins/MERIT_Hydro_v07_Basins_v01_bugfix1/pfaf_level_02/cat_pfaf_71_MERIT_Hydro_v07_Basins_v01_bugfix1.shp
SOURCE_GEOFABRIC_RIVERS_PATH: /project/6079554/data/geospatial-data/MERIT-Basins/MERIT_Hydro_v07_Basins_v01_bugfix1/pfaf_level_02/riv_pfaf_71_MERIT_Hydro_v07_Basins_v01_bugfix1.shp
STREAMFLOW_DATA_PROVIDER: USGS
STREAMFLOW_PROCESSED_PATH: default
STREAMFLOW_RAW_NAME: CHENA R NR TWO RIVERS AK_iv.txt
STREAMFLOW_RAW_PATH: default
STREAM_THRESHOLD: 10
SUMMAFLOW: spatial
SUMMA_EXE: summa_sundials.exe
SUMMA_INSTALL_PATH: default
SWRMSIZE: 10
TAUDEM_DIR: default
TOOL_ACCOUNT: def-mclark-ab
TOOL_CACHE: $SLURM_TMPDIR
UNIFY_SOIL: false
